version: "3.8"
services:
  backend:
    build: ./backend
    container_name: bloomwatch-backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on: []
  frontend:
    build: ./frontend
    container_name: bloomwatch-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend